### ISSUE TITLE
增加下载链接选项

### ISSUE THREAD

**Issue by jostyee** [ShinCurry/Maria#1]
现在可以先打开webui操作，如果能从menu上直接操作更好。。
<img width="163" alt="screen shot 2016-04-21 at 10 35 17" src="https://cloud.githubusercontent.com/assets/88564/14696351/d706e49c-07ac-11e6-95b9-ad714befdf39.png">

**Comment by shincurry** [comment]
下一个版本会加上这个功能。

**Comment by shincurry** [comment]
新版本已发布。 Maria 0.6 Build 1604211
