### ISSUE TITLE
通知中心插件不显示

### ISSUE THREAD

**Issue by ahjsrhj** [ShinCurry/Maria#13]
![](http://ww4.sinaimg.cn/large/801b780agw1f8av4crgnnj208s01x743.jpg)
版本为1.1版

**Comment by shincurry** [comment]
以前修过的 bug 手残又搞出来了。_(:зゝ∠)_

试试这个版本，覆盖安装即可。😊
https://github.com/ShinCurry/Maria/releases/tag/1.1.1
