### ISSUE TITLE
允许了任意程序，运行后还是没反应

### ISSUE THREAD

**Issue by mhqschen** [ShinCurry/Maria#14]

**Comment by csrutil** [comment]
相同的问题，错误信息:

```
➜  ~ /Applications/Maria.app/Contents/MacOS/Maria
[1]    31369 illegal hardware instruction  /Applications/Maria.app/Contents/MacOS/Maria
```

系统信息:

```
ProductName:    Mac OS X
ProductVersion: 10.11.6
BuildVersion:   15G1004

Darwin xxx-Mac-mini.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64
```

Thanks 👍

**Comment by shincurry** [comment]
试一下这个版本 (Maria 1.1.2 build1610126)
https://github.com/ShinCurry/Maria/releases/tag/1.1.2

有问题请尽快反馈。

**Comment by shincurry** [comment]
记录一下问题：
运行后没反应是程序还没初始化界面就 Crash 了，Crash 地方在初始化 `Aria2` 单例的地方，之前写这部分的时候直接强制从 NSUserDefault 获取 aria2 rpc 配置信息，如果程序第一次运行时没有正确的初始化配置信息，就会出现出现崩溃的情况。

另外，从 Xcode 8 开始，使用 `let defaults = UserDefaults(suiteName: "group.windisco.maria")!` 时会出现警告，提示需要在 `suiteName` 前加上加上 Team ID，前几次提交硬编码加上这个之后，发现 Today Widget 又会出问题，现在统一先不加 Team ID，直接忽略警告。
