### ISSUE TITLE
不能隐藏菜单栏图标？？？

### ISSUE THREAD

**Issue by livc** [ShinCurry/Maria#18]

**Comment by shincurry** [comment]
Dock 上的图标可以通过设置取消显示，屏幕顶部状态栏图标无法取消显示。

**Comment by BlueCocoa** [comment]
其实也可以像某截图应用一样，只通过全局快捷键呼出。。
（我个人觉得是没必要的说）

**Comment by shincurry** [comment]
新版可以隐藏状态栏图标了

https://github.com/ShinCurry/Maria/releases/tag/v1.2.3
