### ISSUE TITLE
aria2.h file not found

### ISSUE THREAD

**Issue by wangbiye** [ShinCurry/Maria#19]
找了一下在 Aria2Core 工程里边没有这个文件, 用 Aria2的 Aria2.h不行

**Comment by shincurry** [comment]
`aria2.h` 和 `libaria2-1.28.0-maria.dylib` 文件在最近的提交中被移除了，请自行编译生成。
https://github.com/ShinCurry/Maria/wiki/Contributing

**Comment by wangbiye** [comment]
或许我不用编译源码, 我直接下载了Maria_v1.2_build1611016.zip, 打开之后显示"与 Aria2断开连接", 是因为我本地没有安装 Aria2吗, 但是我用brew install aria2安装Aria2的时候又提示我因为使用OS 10.12报错, 真尴尬

**Comment by shincurry** [comment]
先是静态库的问题，我打包了一份文件，放在这个 Release 里面了，`libaria2-1.28.0-maria.zip` 这个压缩包里有编译需要的文件。
https://github.com/ShinCurry/Maria/releases/tag/1.2

如果不打算做二次开发，只想使用这个软件，直接使用 Release 里打包好的程序就行，可以在设置里勾选 `Use embedded aria2` 选项来开启内置 aria2 模式，目前是测试功能，会有一些问题存在。

我测试了一下手动安装 aria2，可以直接安装不用编译

```
Homebrew 1.0.9
macOS 10.12.1 (16B2657)

brew install aria2

aria2 version 1.27.1
```
