### ISSUE TITLE
Why not rename the "Maria Widget" to "Maria"

### ISSUE THREAD

**Issue by excelwang** [ShinCurry/Maria#2]
Because it is more cute to reduce the redundant information.

**Comment by shincurry** [comment]
OK. next version will change widget title.

**Comment by shincurry** [comment]
new version(0.8.3) app has been published.

widget name 'Maria Widget' will change to 'Maria'
   after reinstalling Maria and **restarting notification center (OR reboot system)**

**Comment by excelwang** [comment]
Thank you very much for the great work!
