### ISSUE TITLE
再次呼出程序主窗口时设定界面总是出现

### ISSUE THREAD

**Issue by wao1201** [ShinCurry/Maria#20]
版本：Maria_v1.2_build1611016

如题目所示，在关闭程序主窗口时已关闭程序设定窗口，可再次呼出程序主窗口时设置窗口再次出现了

**Comment by wao1201** [comment]
退出并再次启动程序后，问题消失了

**Comment by wao1201** [comment]
有时还是会出现此问题，还没掌握规律

**Comment by shincurry** [comment]
我会留意这个问题的，Issue 先保持开启吧
