### ISSUE TITLE
启用自带的 aria2 时候设置端口没有效果

### ISSUE THREAD

**Issue by laizhenwei** [ShinCurry/Maria#21]
chrome 总是说 aria2 未开启，所以我把端口设置成 6800，但是重启 maria 就会变成默认的 6789
版本是 1.2

**Comment by shincurry** [comment]
`设置 -> Aria2 -> 配置 -> .conf 文件 -> rpc-listen-port` 这一项设置内置 aria2 的端口，

`设置 -> Aria2 -> RPC 服务器 -> port` 这一项设置 Maria 连接内置 aria2 的端口，和上面保持一致。

**Comment by shincurry** [comment]
已修复。
