### ISSUE TITLE
内置 aria2不支持其他插件通过 rpc 方式添加下载？

### ISSUE THREAD

**Issue by youthcould** [ShinCurry/Maria#23]
Thanks for your nice job.
RT，chrome 使用这个插件https://chrome.google.com/webstore/detail/aria2c-integration/cnkefpcjiolhnmhfpjbjpidgncnajlmf
开启内置 aria2，端口对应修改好，无法添加下载链接，求指教

PS. 希望可以取消菜单栏图标
多谢

**Comment by shincurry** [comment]
内置 aria2 默认启动了 RPC 的，按理讲应该和独立运行的 aria2 没有区别，
测试可以使用 Aria2 WebUI，所以应该是这个插件的设置的问题？

下一个版本会增加菜单栏图标显示选项。
