### ISSUE TITLE
添加新任务不支持磁力链接了？

### ISSUE THREAD

**Issue by wao1201** [ShinCurry/Maria#24]
http://ww3.sinaimg.cn/large/6bdc3836gw1fb0o25o7tyj20g20auwfb.jpg

Version: Maria 1.2.3

**Comment by shincurry** [comment]
正则表达式忘记加入 magnet 链接和 ed2k 链接了，等会儿发一个新版本。

**Comment by shincurry** [comment]
https://github.com/ShinCurry/Maria/releases/tag/v1.2.4

**Comment by wao1201** [comment]
aria2 都支持电驴了哦 O_O

**Comment by wao1201** [comment]
感谢！

**Comment by shincurry** [comment]
加上之后才发现 aria2 不支持 ed2k 😂
