### ISSUE TITLE
new task crash

### ISSUE THREAD

**Issue by cani1see** [ShinCurry/Maria#27]
new task crush 100%.
version:Maria 1.2.4

[Maria_crush_report.txt](https://github.com/ShinCurry/Maria/files/686469/Maria_crush_report.txt)

**Comment by shincurry** [comment]
复现流程？

**Comment by cani1see** [comment]
点＋或者文件>添加新任务，就crush了

**Comment by BlueCocoa** [comment]
好奇怪，nib初始化的时候居然会跪

**Comment by BlueCocoa** [comment]
@cani1see 提供一下
`shasum -a 256 /Applications/Maria.app/Contents/Resources/Base.lproj/Main.storyboardc/3Py-Pw-Qec-view-Yqt-Qp-1qf.nib`的结果？

正确的应该是`4b054f551cbbd95edc67921c77ff589f9367ca19bde28b158859fd77dcc03830`

**Comment by cani1see** [comment]
@BlueCocoa 对的，是这个值

**Comment by cani1see** [comment]
我是黑苹果，之前用的可能是0.8版，这两天换新的用

**Comment by shincurry** [comment]
试一下完全删除软件再重装，我这里测试是没问题。😰

**Comment by cani1see** [comment]
@ShinCurry 没用 
我试了最近release版本发现只有v1.2.3 v1.2.4有这个问题，1.2.2 Beta3显示和之前不一样。
![maria_feedback](https://cloud.githubusercontent.com/assets/6977594/21676060/38213a6e-d36f-11e6-863a-95a2ccb7006e.png)

**Comment by binss** [comment]
+1。点加号就crash。版本Maria_v1.2.4_build1612231

**Comment by shincurry** [comment]
v1.2.3 新增对 you-get 的支持（虽然目前处于半残废状态），所以添加任务的窗口有变化。
crash report 显示是 NSTextView 未实例化的问题，但是我完全卸载程序重新安装使用并没有发现问题。

另外使用 AppCleaner 删除软件勾选所有找到的配置文件再重新安装试一下，猜测也许是 UserDefault 的问题，以前也有被坑过。

另外我发现下载打包的程序居然显示不明开发者..


issue 先保留着吧，等我考试结束再修。

**Comment by shincurry** [comment]
https://github.com/ShinCurry/Maria/releases/tag/v1.2.5

更多详细可加群反馈 telegram group id: maria_feedback

**Comment by cani1see** [comment]
修好了。不过我需要批量加http，还用的之前版本 。
