### ISSUE TITLE
自定义下载文件夹不起作用吗？

### ISSUE THREAD

**Issue by wao1201** [ShinCurry/Maria#28]
默认是下载到 /Downloads 

我尝试在自定义 aria2.conf 的窗口内添加如下：
Key: dir
Value: /自定义文件夹地址

保存并重启程序，添加新任务后，发现仍然是下载到默认的 /Downloads 下了

是我哪里没做对吗？

（没发现问答页面，只好发在 Issues 下了，抱歉）

**Comment by shincurry** [comment]
`dir` 这个配置项一不小心写死了，下个版本修复。

**Comment by shincurry** [comment]
https://github.com/ShinCurry/Maria/releases/tag/v1.2.5

**Comment by wao1201** [comment]
好的，刚试了下，没问题了
