### ISSUE TITLE
Widget显示任务数量调整bug

### ISSUE THREAD

**Issue by jostyee** [ShinCurry/Maria#3]
没有用。。
<img width="176" alt="a17ab375-5a94-4c26-9b67-f48009567423" src="https://cloud.githubusercontent.com/assets/88564/15418748/06e20068-1e94-11e6-980e-9b2d4725f04a.png">

**Comment by shincurry** [comment]
知道，因为我还没写 😂

**Comment by shincurry** [comment]
已解决。
