### ISSUE TITLE
Maria in status bar mode can lock you out of options menu

### ISSUE THREAD

**Issue by joshkerr** [ShinCurry/Maria#31]
There should be a way to get to the options/preferences menu while the app is in status bar mode. For example, if you incorrectly set the wrong password or connection string on Aria2 from Maria's settings and restart the app while it is in status bar mode, it will be impossible to get back into Maria's preferences. The status bar icon does not show up.

Fix would be to allow the status bar menu to be displayed even if Maria can't connect to Aria2.

**Comment by shincurry** [comment]
left mouse click first on the status bar icon it will show main window, next left click will show the preferences menu if the main window has already been displayed, or you can just have a right mouse  click to open the menu.

**Comment by joshkerr** [comment]
The status bar icon is hidden when Maria can't connect to Aria2. So there is nothing to click.

-josh

**Comment by shincurry** [comment]
I have tested it, nothing happened. Whenever the icon will be displayed on status bar mode.
I guess that Maria was crashed, but not the status bar icon is hidden? 😰

**Comment by joshkerr** [comment]
Launch Maria. Go to preferences and select menu bar only and show speeds. Then go to Aria2 settings and change password. Click the restart Aria2 button. The whole app should reset but this time it won't connect to Aria2. The main app window will display but the menu bar icon won't display. If you click to another window Maria will disappear and there is no way to get it back.

-josh

**Comment by shincurry** [comment]
OK, I got it, a tiny bug. 😂

<img width="189" alt="2017-01-26 14 12 31" src="https://cloud.githubusercontent.com/assets/4946624/22321656/84556dde-e3d1-11e6-9247-ab713a365bd2.png">

**Comment by shincurry** [comment]
fixed. v1.2.7
