### ISSUE TITLE
出现 一个残影

### ISSUE THREAD

**Issue by coolicer** [ShinCurry/Maria#36]
<img width="206" alt="wx20170401-092129 2x" src="https://cloud.githubusercontent.com/assets/811078/24573899/2437a218-16bd-11e7-93e7-120e84977fb7.png">
在页面上会出现一个残影，我看了是maria的，是我电脑坏了吗？

**Comment by shincurry** [comment]
我也遇到过这个问题的，但是感觉不是软件本身的问题。😳

**Comment by coolicer** [comment]
@ShinCurry 好吧，相信你😁
