### ISSUE TITLE
图标太丑了啊

### ISSUE THREAD

**Issue by lrvy** [ShinCurry/Maria#38]
能不能换一个好看点的啊QAQ

**Comment by xfoxfu** [comment]
Duplicate as #30 .

You should have searched before you open an issue.

**Comment by shincurry** [comment]
<img width="548" alt="2017-04-23 17 24 11" src="https://cloud.githubusercontent.com/assets/4946624/25312363/c27e36ec-2849-11e7-9410-c2ea9c46f6ff.png">

如果你觉得图标丑了，也许你可以自己尝试设计一个能看的。说实话，我并不想要那种一个圆圈里面套上字母的常规图标。

If you think the icon is ugly, maybe you can try to design another one by yourself, then show to us.
To be honest, I do noooooooooot want a conventional icon with letters on a circle.

**Comment by egoist** [comment]
这种 issue 如果你没有给出解决方案或者直接 PR 基本和在微博上吐槽没什么区别。

**Comment by lrvy** [comment]
恩 是的，我还是自己先画个图标吧。
