### ISSUE TITLE
trackpad不能上下滚动列表

### ISSUE THREAD

**Issue by jostyee** [ShinCurry/Maria#4]
RT，只能靠方向键查看。。

**Comment by shincurry** [comment]
这个问题经常出现吗？我没有遇到过这个问题。
你试试重启软件或者重启系统？

**Comment by jostyee** [comment]
重启应用不能稳定复现，我先关了吧。。

**Comment by jostyee** [comment]
0.8.5 复现了。。

**Comment by shincurry** [comment]
这个问题似乎已经解决了，

**[Bug 复现]** 当打开 App 显示任务的数量超过窗口可显示范围的时候，就无法向下滑动。
之前是把 H/V Scroller 都关掉了的，现在重新开启 Vertical Scroller ，似乎不会再出现这个问题了。

v0.8.6 build1606081 已修复 Bug

issue 暂时开着吧我再观察一段时间。
