### ISSUE TITLE
Restart按钮无效

### ISSUE THREAD

**Issue by jostyee** [ShinCurry/Maria#5]
RT，只能打开 https://github.com/ziahamza/webui-aria2 网页重启任务

**Comment by shincurry** [comment]
因为根本没有做这部分功能。

aria2 rpc 并没有提供重新启动已停止或者出错下载任务的 API，只能暂停和恢复下载。
问过 aria2 作者，也说没有方便的方法，（而且回复给我的感觉是没必要有这个功能？[黑人问号???]）
所以暂时只能这样。

有时间会研究一下 webui-aria2 的解决方法。

issue 等它一直开着吧。
