### ISSUE TITLE
希望提供一个傻瓜包，类似Aria2GUI

### ISSUE THREAD

**Issue by youthcould** [ShinCurry/Maria#8]
RT，希望提供傻瓜包，直接安装maria则aric2等等安装设置都全搞定，卸载Maria也同理
谢谢

**Comment by Mingyi** [comment]
即使不是傻瓜包，也没看明白怎么使用，门槛太高了吗？

**Comment by youthcould** [comment]
非也，只是希望尽量简便。使用的人更方便，谢谢

**Comment by shincurry** [comment]
目前在尝试着嵌入 C++ 源代码集成 aria2，不过因为自身技术实力，可能做不出来。
推荐 Maria、 YAAW 、 Aria2 & YAAW 等 GUI 和 aria2 分开独立使用。

**Comment by zanderzhng** [comment]
做成sourcetree那样，既可以用它打包的git，也可以用自己安装的。

**Comment by shincurry** [comment]
我希望的是 Maria 直接接入 aria2 的内部接口，而不是通过 RPC 方式，但是目前遇到很多问题，真要做可能要自己修改源码了。

直接打包二进制包的确是可以，只不过觉得目前这样独立分开运行更好，之前说过因为 aria2 有些 API 
没有，Maria 无法完全的替代 webui。

**Comment by xjbeta** [comment]
aria2自己的rpc问题太多   完全不能实现精确控制   只能全部刷新
那两个webui也是用的rpc   没区别

**Comment by shincurry** [comment]
试一下这个测试版本
https://github.com/ShinCurry/Maria/releases/tag/v1.1.3beta
以 `libaria2` 静态库的方式集成了 aria2，可能会有 Crash
